"""Database model and CRUD operations for tracking article files and their SEO metadata."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_article.ipynb.

# %% auto #0
__all__ = ['insert_article', 'get_article_by_id', 'get_article_by_path', 'get_articles_by_website', 'delete_article',
           'update_article']

# %% ../nbs/03_article.ipynb #fa7b3269
from sqlmodel import SQLModel, Field, create_engine, Session, select, Column
from sqlalchemy import JSON
from datetime import datetime, date
from .sqlite_db import  get_session

# %% ../nbs/03_article.ipynb #51f1f26c
class Article(SQLModel, table=True):
    "An article file tracked for SEO optimization."
    __table_args__ = {"extend_existing": True}
    id: int | None = Field(default=None, primary_key=True)
    website_id: int = Field(foreign_key="website.id") # Parent website
    file_path: str                                     # Path to .md or .ipynb file
    url: str | None = None                             # Public URL of the article
    focus_keyword: str | None = None                   # Primary SEO keyword
    secondary_keywords: list[str] | None = Field(default=None, sa_column=Column(JSON))
    target_goal: str | None = None                     # Optimization goal
    last_optimized: datetime | None = None             # Last optimization timestamp
    created_at: datetime = Field(default_factory=datetime.now)

# %% ../nbs/03_article.ipynb #8703aac9
def insert_article(session:Session,   # Active database session
                   article:Article    # Article instance to insert
                  ) -> Article:
    "Insert a new article into the database."
    session.add(article)
    session.commit()
    session.refresh(article)
    return article


# %% ../nbs/03_article.ipynb #3f958518
def get_article_by_id(session:Session,  # Active database session
                      article_id:int    # Article primary key
                     ) -> Article | None:
    "Get an article by its ID."
    return session.get(Article, article_id)


# %% ../nbs/03_article.ipynb #33635cc8
def get_article_by_path(session:Session, # Active database session
                        file_path:str    # File path to match
                       ) -> Article | None:
    "Get an article by its file path."
    return session.exec(select(Article).where(Article.file_path == file_path)).first()


# %% ../nbs/03_article.ipynb #145f3db4
def get_articles_by_website(session:Session, # Active database session
                            website_id:int   # Parent website ID
                           ) -> list[Article]:
    "Get all articles belonging to a website."
    return session.exec(select(Article).where(Article.website_id == website_id)).all()


# %% ../nbs/03_article.ipynb #77e8a592
def delete_article(session:Session, # Active database session
                   article_id:int   # Article to delete
                  ) -> None:
    "Delete an article by ID. Raises ValueError if not found."
    article = session.get(Article, article_id)
    if article is None: raise ValueError(f"Article with id {article_id} not found")
    session.delete(article)
    session.commit()

# %% ../nbs/03_article.ipynb #a84d5be1f002fc4d
def update_article(session:Session,                          # Active database session
                   article_id:int,                           # Article to update
                   focus_keyword:str|None=None,              # New focus keyword
                   secondary_keywords:list[str]|None=None,   # New secondary keywords
                   target_goal:str|None=None,                # New target goal
                   url:str|None=None                         # New public URL
                  ) -> Article:
    "Update article fields and set last_optimized to now. Raises ValueError if not found."
    article = session.get(Article, article_id)
    if article is None: raise ValueError(f"Article with id {article_id} not found")
    if focus_keyword: article.focus_keyword = focus_keyword
    if secondary_keywords: article.secondary_keywords = secondary_keywords
    if target_goal: article.target_goal = target_goal
    if url: article.url = url
    article.last_optimized = datetime.now()
    session.add(article)
    session.commit()
    session.refresh(article)
    return article
