"""Query, filter, and persist Google Search Console analytics data in SQLite."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_gsc_storage.ipynb.

# %% auto #0
__all__ = ['filter_site', 'filter_dates', 'filter_dimension', 'filter_exclude_pages', 'AnalyticsSummary', 'normalize_url',
           'parse_gsc_row', 'store_gsc_data', 'get_top_queries', 'get_top_pages', 'get_wins',
           'get_top_queries_excluding_pages', 'get_page_analytics', 'get_analytics_by_date_range', 'get_trends',
           'get_analytics_by', 'store_single_date', 'store_date_range', 'iter_dates', 'get_missing_dates',
           'sync_missing_dates', 'daily_sync', 'compare_date_ranges', 'get_country_breakdown']

# %% ../nbs/05_gsc_storage.ipynb #9ba81a16
from sqlmodel import Session, select
from .models import GSCAnalytics
from datetime import datetime, timedelta
from functools import partial
from fastcore.basics import compose
from sqlalchemy import func, not_, or_
from .sqlite_db import  get_session
from .models import GSCAnalytics
from .gsc_client import GSCAuth
from .gsc_client import get_date_range

# %% ../nbs/05_gsc_storage.ipynb #e3c41198
def filter_site(query,  # SQLModel query
                site_url: str  # GSC property URL
                ):
    "Filter query by site URL."
    return query.where(GSCAnalytics.site_url == site_url)


def filter_dates(query,  # SQLModel query
                 start: str,  # Start date (YYYY-MM-DD)
                 end: str  # End date (YYYY-MM-DD)
                 ):
    "Filter query by date range."
    return query.where(GSCAnalytics.date.between(start, end))


def filter_dimension(query,  # SQLModel query
                     dimension: str,  # GSCAnalytics field name
                     value: str  # Value to match
                     ):
    "Filter query by a specific dimension value."
    return query.where(getattr(GSCAnalytics, dimension) == value)


def filter_exclude_pages(query,  # SQLModel query
                         exclude_pages: list[str]  # Page path substrings to exclude
                         ):
    "Exclude rows where page contains any of the given substrings."
    return query.where(not_(or_(*[GSCAnalytics.page.contains(p) for p in exclude_pages])))


# %% ../nbs/05_gsc_storage.ipynb #f5c2c658
from sqlmodel import SQLModel


class AnalyticsSummary(SQLModel):
    query: str
    clicks: int
    impressions: int

# %% ../nbs/05_gsc_storage.ipynb #bf4b349f
from urllib.parse import unquote


def normalize_url(url: str) -> str:
    """Normalize URL by decoding percent-encoding and standardizing separators"""
    url = unquote(url)
    url = url.replace("-", " ").replace("_", " ")
    return url


# %% ../nbs/05_gsc_storage.ipynb #13abf339
def parse_gsc_row(row:dict,      # Raw GSC API row
                  site_url:str,  # GSC property URL
                  date:str       # Date of the row (YYYY-MM-DD)
                 ) -> GSCAnalytics:
    "Parse a raw GSC API row into a GSCAnalytics instance."
    dims = dict(zip(("query", "page", "country", "device"), row["keys"]))
    return GSCAnalytics(site_url=site_url, date=date,
                        query=dims.get("query"), page=dims.get("page"),
                        country=dims.get("country"), device=dims.get("device"),
                        clicks=row["clicks"], impressions=row["impressions"],
                        ctr=row["ctr"], position=row["position"])


# %% ../nbs/05_gsc_storage.ipynb #b82b12c4
from sqlalchemy.dialects.sqlite import insert

def store_gsc_data(session:Session,  # Active database session
                   site_url:str,     # GSC property URL
                   date:str,         # Date of the data (YYYY-MM-DD)
                   rows:list[dict]   # Raw GSC API rows
                  ) -> None:
    "Store GSC rows with upsert (update on conflict)."
    for row in rows:
        record = parse_gsc_row(row, site_url, date)
        stmt = insert(GSCAnalytics).values(**record.model_dump(exclude={"id"}))
        stmt = stmt.on_conflict_do_update(
            index_elements=["site_url", "date", "query", "page", "country", "device"],
            set_={"clicks": record.clicks, "impressions": record.impressions,
                  "ctr": record.ctr, "position": record.position}
        )
        session.exec(stmt)
    session.commit()


# %% ../nbs/05_gsc_storage.ipynb #cf40d14b
def get_top_queries(session: Session,  # Active database session
                    site_url: str,  # GSC property URL
                    start_date: str,  # Start date (YYYY-MM-DD)
                    end_date: str,  # End date (YYYY-MM-DD)
                    country: str | None = None,  # Filter by country code
                    page_path: str | None = None,  # Filter by page path substring
                    limit: int = 10,  # Max rows to return
                    sort_by: str = "clicks"  # Sort by 'clicks' or 'impressions'
                    ) -> list[dict]:
    "Get top performing queries, optionally filtered by country and page."
    base = select(GSCAnalytics.query,
                  func.sum(GSCAnalytics.clicks).label("total_clicks"),
                  func.sum(GSCAnalytics.impressions).label("total_impressions"),
                  func.avg(GSCAnalytics.position).label("avg_position"),
                  func.avg(GSCAnalytics.ctr).label("avg_ctr"))
    filters = [partial(filter_site, site_url=site_url),
               partial(filter_dates, start=start_date, end=end_date)]
    if country: filters.append(partial(filter_dimension, dimension="country", value=country))
    if page_path: filters.append(lambda q: q.where(GSCAnalytics.page.contains(page_path)))
    sort_col = func.sum(GSCAnalytics.impressions) if sort_by == "impressions" else func.sum(GSCAnalytics.clicks)
    query = (compose(*filters)(base)
             .where(GSCAnalytics.query.isnot(None))
             .group_by(GSCAnalytics.query)
             .order_by(sort_col.desc())
             .limit(limit))
    return [row._asdict() for row in session.exec(query)]


# %% ../nbs/05_gsc_storage.ipynb #7d56cafe433f7d3
def get_top_pages(session: Session, site_url: str, start_date: str, end_date: str,
                  country: str | None = None, limit: int = 20, sort_by: str = "clicks") -> list[dict]:
    "Get top performing pages by clicks or impressions."
    base = select(GSCAnalytics.page,
                  func.sum(GSCAnalytics.clicks).label("total_clicks"),
                  func.sum(GSCAnalytics.impressions).label("total_impressions"),
                  func.avg(GSCAnalytics.position).label("avg_position"),
                  func.avg(GSCAnalytics.ctr).label("avg_ctr"))
    filters = [partial(filter_site, site_url=site_url),
               partial(filter_dates, start=start_date, end=end_date)]
    if country: filters.append(partial(filter_dimension, dimension="country", value=country))
    sort_col = func.sum(GSCAnalytics.impressions) if sort_by == "impressions" else func.sum(GSCAnalytics.clicks)
    query = (compose(*filters)(base)
             .where(GSCAnalytics.page.isnot(None))
             .group_by(GSCAnalytics.page)
             .order_by(sort_col.desc())
             .limit(limit))
    return [row._asdict() for row in session.exec(query)]


# %% ../nbs/05_gsc_storage.ipynb #1de8de5b03c02569
def get_wins(session: Session, site_url: str, start_date: str, end_date: str,
             min_impressions: int = 100, min_position: float = 10.0,
             max_position: float = 50.0, country: str | None = None,
             page_url: str | None = None, limit: int = 20) -> list[dict]:
    "Get high-impression, low-ranking keyword opportunities."
    base = select(GSCAnalytics.query,
                  func.sum(GSCAnalytics.clicks).label("total_clicks"),
                  func.sum(GSCAnalytics.impressions).label("total_impressions"),
                  func.avg(GSCAnalytics.position).label("avg_position"),
                  func.avg(GSCAnalytics.ctr).label("avg_ctr"))
    filters = [partial(filter_site, site_url=site_url),
               partial(filter_dates, start=start_date, end=end_date)]
    if country: filters.append(partial(filter_dimension, dimension="country", value=country))
    if page_url: filters.append(lambda q: q.where(GSCAnalytics.page == page_url))
    query = (compose(*filters)(base)
             .where(GSCAnalytics.query.isnot(None))
             .group_by(GSCAnalytics.query)
             .having(func.sum(GSCAnalytics.impressions) >= min_impressions,
                     func.avg(GSCAnalytics.position) >= min_position,
                     func.avg(GSCAnalytics.position) <= max_position)
             .order_by(func.sum(GSCAnalytics.impressions).desc())
             .limit(limit))
    return [row._asdict() for row in session.exec(query)]



# %% ../nbs/05_gsc_storage.ipynb #bac24352
def get_top_queries_excluding_pages(session: Session,  # Active database session
                                    site_url: str,  # GSC property URL
                                    start_date: str,  # Start date (YYYY-MM-DD)
                                    end_date: str,  # End date (YYYY-MM-DD)
                                    exclude_pages: list[str],  # Page substrings to exclude
                                    country: str | None = None,  # Filter by country code
                                    limit: int = 10  # Max rows to return
                                    ) -> list[dict]:
    "Get top queries excluding specific pages."
    base = select(GSCAnalytics.query,
                  func.sum(GSCAnalytics.clicks).label("total_clicks"),
                  func.sum(GSCAnalytics.impressions).label("total_impressions"))
    filters = [partial(filter_site, site_url=site_url),
               partial(filter_dates, start=start_date, end=end_date),
               partial(filter_exclude_pages, exclude_pages=exclude_pages)]
    if country: filters.append(partial(filter_dimension, dimension="country", value=country))
    query = (compose(*filters)(base)
             .where(GSCAnalytics.query.isnot(None))
             .group_by(GSCAnalytics.query)
             .order_by(func.sum(GSCAnalytics.clicks).desc())
             .limit(limit))
    return [row._asdict() for row in session.exec(query)]


# %% ../nbs/05_gsc_storage.ipynb #437a9e6a
def get_page_analytics(session: Session,  # Active database session
                       site_url: str,  # GSC property URL
                       page_path: str,  # Partial page path to match
                       start_date: str,  # Start date (YYYY-MM-DD)
                       end_date: str  # End date (YYYY-MM-DD)
                       ) -> dict:
    "Get aggregated analytics and top queries for a specific page."
    filters = compose(
        partial(filter_site, site_url=site_url),
        partial(filter_dates, start=start_date, end=end_date),
    )
    base = filters(select(
        func.sum(GSCAnalytics.clicks).label("total_clicks"),
        func.sum(GSCAnalytics.impressions).label("total_impressions"),
        func.avg(GSCAnalytics.position).label("avg_position"),
        func.avg(GSCAnalytics.ctr).label("avg_ctr"),
    )).where(GSCAnalytics.page.contains(page_path))
    row = session.exec(base).first()

    top_queries = session.exec(
        filters(select(GSCAnalytics.query, func.sum(GSCAnalytics.clicks).label("clicks"))
                .where(GSCAnalytics.page.contains(page_path), GSCAnalytics.query.isnot(None))
                .group_by(GSCAnalytics.query)
                .order_by(func.sum(GSCAnalytics.clicks).desc())
                .limit(10))
    ).all()

    return {"page_path": page_path,
            "total_clicks": row.total_clicks or 0,
            "total_impressions": row.total_impressions or 0,
            "avg_position": row.avg_position or 0,
            "avg_ctr": row.avg_ctr or 0,
            "top_queries": [q for q, _ in top_queries]}



# %% ../nbs/05_gsc_storage.ipynb #cd437b68
def get_analytics_by_date_range(session: Session,  # Active database session
                                site_url: str,  # GSC property URL
                                start_date: str,  # Start date (YYYY-MM-DD)
                                end_date: str  # End date (YYYY-MM-DD)
                                ) -> list[GSCAnalytics]:
    "Get all raw GSC analytics rows for a date range."
    return session.exec(
        compose(partial(filter_site, site_url=site_url),
                partial(filter_dates, start=start_date, end=end_date)
                )(select(GSCAnalytics))
    ).all()


# %% ../nbs/05_gsc_storage.ipynb #1d977048
def get_trends(session: Session,  # Active database session
               site_url: str,  # GSC property URL
               start_date: str,  # Start date (YYYY-MM-DD)
               end_date: str,  # End date (YYYY-MM-DD)
               dimension: str | None = None  # Optional dimension to group by
               ) -> list[dict]:
    "Get click/impression trends over time, optionally grouped by a dimension."
    columns = [GSCAnalytics.date,
               func.sum(GSCAnalytics.clicks).label("clicks"),
               func.sum(GSCAnalytics.impressions).label("impressions"),
               func.avg(GSCAnalytics.position).label("avg_position"),
               func.avg(GSCAnalytics.ctr).label("avg_ctr")]
    group_by = [GSCAnalytics.date]
    if dimension:
        dim_col = getattr(GSCAnalytics, dimension)
        columns.insert(1, dim_col)
        group_by.append(dim_col)
    query = (compose(partial(filter_site, site_url=site_url),
                     partial(filter_dates, start=start_date, end=end_date))
             (select(*columns))
             .group_by(*group_by)
             .order_by(GSCAnalytics.date))
    return [row._asdict() for row in session.exec(query)]


# %% ../nbs/05_gsc_storage.ipynb #2b0fe945
def get_analytics_by(session: Session,  # Active database session
                     site_url: str,  # GSC property URL
                     start_date: str,  # Start date (YYYY-MM-DD)
                     end_date: str,  # End date (YYYY-MM-DD)
                     dimension: str,  # GSCAnalytics field to filter by
                     value: str  # Value to match
                     ) -> list[AnalyticsSummary]:
    "Get query-level analytics filtered by a specific dimension value."
    base = select(GSCAnalytics.query,
                  func.sum(GSCAnalytics.clicks).label("clicks"),
                  func.sum(GSCAnalytics.impressions).label("impressions"))
    query = (compose(partial(filter_site, site_url=site_url),
                     partial(filter_dates, start=start_date, end=end_date),
                     partial(filter_dimension, dimension=dimension, value=value))
             (base).group_by(GSCAnalytics.query))
    return [AnalyticsSummary(**row._asdict()) for row in session.exec(query)]


# %% ../nbs/05_gsc_storage.ipynb #c41b1113
from .gsc_client import fetch_gsc_data
import time


def store_single_date(session:Session, # Active database session
                      auth:GSCAuth,    # Authenticated GSCAuth instance
                      site_url:str,    # GSC property URL
                      date:str         # Date to fetch and store (YYYY-MM-DD)
                     ) -> int:
    "Fetch and store GSC data for a single date. Returns number of records stored."
    rows = fetch_gsc_data(auth, site_url, date, date)
    store_gsc_data(session, site_url, date, rows)
    return len(rows)

# %% ../nbs/05_gsc_storage.ipynb #5bc21268b1817347
def _sync_dates(session: Session,  # Active database session
                auth: GSCAuth,  # Authenticated GSCAuth instance
                site_url: str,  # GSC property URL
                dates: list[str]  # List of dates to sync (YYYY-MM-DD)
                ) -> dict:
    "Fetch and store GSC data for a list of dates, returning a results summary."
    results = {"successful": [], "failed": [], "total_records": 0}
    for date in dates:
        try:
            count = store_single_date(session, auth, site_url, date)
            results["successful"].append(date)
            results["total_records"] += count
            print(f"Synced {date}: {count} records")
        except Exception as e:
            results["failed"].append({"date": date, "error": str(e)})
            print(f"Failed {date}: {e}")
        time.sleep(1)
    return results


# %% ../nbs/05_gsc_storage.ipynb #3105675a
def store_date_range(session: Session, auth: GSCAuth, site_url: str, start_date: str, end_date: str) -> dict:
    "Fetch and store GSC data for all dates in range."
    return _sync_dates(session, auth, site_url, iter_dates(start_date, end_date))



# %% ../nbs/05_gsc_storage.ipynb #5fae22d6
from datetime import date, timedelta


def iter_dates(start_date: str,  # Start date (YYYY-MM-DD)
               end_date: str  # End date (YYYY-MM-DD)
               ) -> list[str]:
    "Generate all dates between start and end inclusive."

    start_d = datetime.strptime(start_date, "%Y-%m-%d").date()
    end_d = datetime.strptime(end_date, "%Y-%m-%d").date()
    return [(start_d + timedelta(days=i)).strftime("%Y-%m-%d")
            for i in range((end_d - start_d).days + 1)]


def get_missing_dates(session: Session,  # Active database session
                      site_url: str,  # GSC property URL
                      start_date: str,  # Start date (YYYY-MM-DD)
                      end_date: str  # End date (YYYY-MM-DD)
                      ) -> list[str]:
    "Return dates in range that have no stored GSC data."
    stored = set(session.exec(
        select(GSCAnalytics.date).where(GSCAnalytics.site_url == site_url).distinct()
    ).all())
    return sorted(set(iter_dates(start_date, end_date)) - stored)




# %% ../nbs/05_gsc_storage.ipynb #4269764d
def sync_missing_dates(session: Session, auth: GSCAuth, site_url: str, start_date: str, end_date: str) -> dict:
    "Fetch and store GSC data for missing dates only."
    return _sync_dates(session, auth, site_url, get_missing_dates(session, site_url, start_date, end_date))

# %% ../nbs/05_gsc_storage.ipynb #f037e7b3
def daily_sync(session: Session,  # Active database session
               auth: GSCAuth,  # Authenticated GSCAuth instance
               sites: list[str]  # List of GSC property URLs to sync
               ) -> dict:
    "Sync missing GSC data for all sites up to today."
    _, end = get_date_range("today")
    return {site: sync_missing_dates(session, auth, site,
                                     min(get_missing_dates(session, site, "2020-01-01", end), default=end),
                                     end)
            for site in sites}

# %% ../nbs/05_gsc_storage.ipynb #58afee0a297eae06
def compare_date_ranges(session: Session,  # Active database session
                        site_url: str,  # GSC property URL
                        start1: str,  # First period start date (YYYY-MM-DD)
                        end1: str,  # First period end date (YYYY-MM-DD)
                        start2: str,  # Second period start date (YYYY-MM-DD)
                        end2: str,  # Second period end date (YYYY-MM-DD)
                        page_url: str | None = None  # Optional specific page to compare
                        ) -> dict:
    "Compare GSC metrics between two date ranges, optionally for a specific page."
    # Get metrics for period 1
    base = select(
        func.sum(GSCAnalytics.clicks).label("clicks"),
        func.sum(GSCAnalytics.impressions).label("impressions"),
        func.avg(GSCAnalytics.position).label("avg_position"),
        func.avg(GSCAnalytics.ctr).label("avg_ctr")
    )
    filters1 = compose(
        partial(filter_site, site_url=site_url),
        partial(filter_dates, start=start1, end=end1)
    )
    if page_url:
        filters1 = compose(filters1, lambda q: q.where(GSCAnalytics.page == page_url))
    row1 = session.exec(filters1(base)).first()

    # Get metrics for period 2
    filters2 = compose(
        partial(filter_site, site_url=site_url),
        partial(filter_dates, start=start2, end=end2)
    )
    if page_url:
        filters2 = compose(filters2, lambda q: q.where(GSCAnalytics.page == page_url))
    row2 = session.exec(filters2(base)).first()

    def to_dict(row):
        return {
            "clicks": row.clicks or 0,
            "impressions": row.impressions or 0,
            "avg_position": round(row.avg_position or 0, 2),
            "avg_ctr": round((row.avg_ctr or 0) * 100, 2)
        }

    return {
        "page_url": page_url,
        "period1": {"start": start1, "end": end1, **to_dict(row1)},
        "period2": {"start": start2, "end": end2, **to_dict(row2)}
    }

# %% ../nbs/05_gsc_storage.ipynb #9bf3af91d6697f29
def get_country_breakdown(session: Session,  # Active database session
                          site_url: str,  # GSC property URL
                          start_date: str,  # Start date (YYYY-MM-DD)
                          end_date: str,  # End date (YYYY-MM-DD)
                          page_url: str | None = None,  # Optional specific page to filter
                          limit: int = 20  # Max number of countries to return
                          ) -> list[dict]:
    "Get traffic metrics grouped by country, optionally for a specific page."
    base = select(
        GSCAnalytics.country,
        func.sum(GSCAnalytics.clicks).label("clicks"),
        func.sum(GSCAnalytics.impressions).label("impressions"),
        func.avg(GSCAnalytics.position).label("avg_position"),
        func.avg(GSCAnalytics.ctr).label("avg_ctr")
    )
    filters = compose(
        partial(filter_site, site_url=site_url),
        partial(filter_dates, start=start_date, end=end_date)
    )
    if page_url:
        filters = compose(filters, lambda q: q.where(GSCAnalytics.page == page_url))

    query = (filters(base)
             .where(GSCAnalytics.country.isnot(None))
             .group_by(GSCAnalytics.country)
             .order_by(func.sum(GSCAnalytics.clicks).desc())
             .limit(limit))

    return [row._asdict() for row in session.exec(query)]
