"""SQlModel Models of the Website."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_models.ipynb.

# %% auto #0
__all__ = ['get_all_websites', 'delete_website', 'add_or_update_website', 'print_websites']

# %% ../nbs/01_models.ipynb #8af54b8e
from sqlmodel import Field, SQLModel, UniqueConstraint, Session, select
from datetime import datetime
from .sqlite_db import get_session
import re
from pydantic import field_validator
from pathlib import Path

# %% ../nbs/01_models.ipynb #193c2559
class Website(SQLModel, table=True):
    "Represents a website being tracked for SEO analysis."
    __table_args__ = {"extend_existing": True}
    id: int | None = Field(default=None, primary_key=True)
    url: str = Field(unique=True)  # Unique website URL
    name: str  # Display name of the website
    desc: str | None = None  # Optional description
    lang: str = "en"  # Language code (e.g. 'en', 'ar')
    created_at: datetime = Field(default_factory=datetime.now)
    site_type: str
    content_dir: str = ""

    @field_validator("url")
    @classmethod
    def validate_url(cls, v: str) -> str:
        from urllip.parse import urlparse

        parsed = urlparse(v)
        if not all([parsed.scheme, parsed.netloc]):
            raise ValueError(f"Invalid URL: {v}")
        return v

    @field_validator("name")
    @classmethod
    def validate_name(cls, v: str) -> str:
        if not v or len(v.strip()) < 1:
            raise ValueError(f"Invalid Name: {v}")
        return v

    @field_validator("lang")
    @classmethod
    def validate_lang(cls, v: str) -> str:
        if not re.match(r"^[a-z]{2}(-[A-Z]{2})?$", v):
            raise ValueError(f"Invalid Language Code: {v}")
        return v

# %% ../nbs/01_models.ipynb #c4038cd8
def get_all_websites(session: Session  # Active database session
                     ) -> list[Website]:
    "Return all websites from the database."
    return session.exec(select(Website)).all()

# %% ../nbs/01_models.ipynb #1be5e48c
def delete_website(session: Session,  # Active database session
                   website_id: int  # ID of the website to delete
                   ) -> None:
    "Delete a website by ID, raises ValueError if not found."
    website = session.get(Website, website_id)
    if website is None:
        raise ValueError(f"Website with id {website_id} not found")
    session.delete(website)
    session.commit()

# %% ../nbs/01_models.ipynb #eb118f98abf8b2d
def add_or_update_website(
        session: Session,  #Active database session
        url: str,  #Website URL (must include https://)
        name: str,  #Display name for the Website
        site_type: str,  #Type: 'quarto','astro',etc.
        desc: str = "",  #Optional description
        lang: str = "en",  #Language code
        content_dir: str = "",  #Local path to content directory
        website_id: int | None = None  #ID to update exisiting.
) -> Website:
    """Add a new website or update an exisiting one."""
    with get_session() as session:
        if website_id:
            website = session.get(Website, website_id)
            if website is None:
                raise ValueError(f"Website with id {website_id} not found")
        else:
            website = session.exec(select(Website).where(Website.url == url)).first()

        if website:
            #update existing
            website.name = name
            website.site_type = site_type
            website.desc = desc or website.desc
            website.lang = lang
            website.content_dir = content_dir
        else:
            #Create New Website
            website = Website(
                url=url,
                name=name,
                site_type=site_type,
                desc=desc,
                lang=lang,
                content_dir=content_dir
            )
            session.add(website)
        session.commit()
        session.refresh(website)
        return website


# %% ../nbs/01_models.ipynb #deb5e8d28e4d2b05
from rich.table import Table
from rich import print as rprint


def print_websites(websites: list[Website]) -> None:
    "Print websites as a rich table."
    if not websites:
        rprint("[yellow]No websites found. Add one with: seo-rat-add-website[/yellow]")
        return
    table = Table(title="🌐 Websites")
    table.add_column("ID", justify="right", style="dim")
    table.add_column("Name", style="cyan")
    table.add_column("URL")
    table.add_column("Type", style="green")
    table.add_column("Lang", justify="center")
    for w in websites:
        table.add_row(str(w.id), w.name, w.url, w.site_type, w.lang)
    rprint(table)

# %% ../nbs/01_models.ipynb #d4c8eab3
class GSCAnalytics(SQLModel, table=True):
    "Google Search Console analytics data for a site, query, page, and device combination."
    __table_args__ = (
        UniqueConstraint("site_url", "date", "query", "page", "country", "device"),
        {"extend_existing": True},
    )
    id: int | None = Field(default=None, primary_key=True)
    site_url: str  # The verified GSC property URL
    date: str  # Date of the analytics record (YYYY-MM-DD)
    query: str | None = None  # Search query keyword
    page: str | None = None  # Page URL
    country: str | None = None  # Country code (e.g. 'usa')
    device: str | None = None  # Device type (e.g. 'mobile')
    clicks: int = 0
    impressions: int = 0
    ctr: float = 0.0
    position: float = 0.0
    created_at: datetime = Field(default_factory=datetime.now)



# %% ../nbs/01_models.ipynb #1fd437e0
class IndexStatus(SQLModel, table=True):
    "Google Search Console indexing status for a specific page."
    __table_args__ = {"extend_existing": True}
    id: int | None = Field(default=None, primary_key=True)
    site_url: str  # The verified GSC property URL
    page_url: str  # The specific page being checked
    verdict: str  # Overall indexing verdict (e.g. 'PASS', 'FAIL')
    coverage_state: str | None = None  # Coverage state from GSC
    last_crawl_time: str | None = None  # Last time Google crawled the page
    indexing_state: str | None = None  # Whether the page is indexed
    robots_txt_state: str | None = None  # Robots.txt blocking status
    checked_at: datetime = Field(default_factory=datetime.now)


