"""Extract and parse JSON-LD schema markup from web pages."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/14_schema_extractor.ipynb.

# %% auto #0
__all__ = ['extract_faq_queries']

# %% ../nbs/14_schema_extractor.ipynb #e9e9dc9b
from sqlmodel import Session, select
from .article import get_article_by_path, insert_article, Article
from .sqlite_db import get_session
from .models import Website
from .content_mapper import map_all_urls_to_files, fetch_sitemap_urls

# %% ../nbs/14_schema_extractor.ipynb #9fa5f0bb
from .gsc_storage import get_top_queries
from .article import get_articles_by_website
from .gsc_client import get_date_range

# %% ../nbs/14_schema_extractor.ipynb #8bbd92a1
import re

_ARABIC_RE = re.compile(r"[\u0600-\u06FF]")

# English question word patterns
_EN_Q_WORDS = re.compile(
    r"^(what|who|why|when|where|which|how|can|is|are|do|does|did|will|should|"
    r"could|would|may|might|shall)\b", re.IGNORECASE)

# Arabic question word patterns — requires space after particle to avoid matching nouns
_AR_Q_WORDS = re.compile(
    r"^("
    r"ما (هو|هي|هم|هي|الح|ال|يع|تع|يج|ه[ا-ي])|"
    r"ماذا |من أين |من اين |أين |اين |كيف |كيفية |كيفيه |"
    r"هل |لماذا |كم |بماذا |لمن |متى |أي |من "
    r")")


def _is_arabic(text: str  # Text to check
               ) -> bool:
    "Return True if more than 30% of characters are Arabic."
    return len(_ARABIC_RE.findall(text)) > len(text) * 0.3


def _is_question(query: str  # Search query
                 ) -> bool:
    "Return True if the query is a question in Arabic or English."
    q = query.strip()
    if q.endswith("?") or q.endswith("؟"): return True
    return bool(_AR_Q_WORDS.match(q) if _is_arabic(q) else _EN_Q_WORDS.match(q))


def extract_faq_queries(rows: list[dict] | list[str]  # GSC query dicts or plain strings
                        ) -> list[str]:
    "Filter GSC queries that are questions in Arabic or English."
    queries = (r["query"] if isinstance(r, dict) else r for r in rows)
    return list(filter(_is_question, queries))


