"""Validate structured data (JSON-LD) against schema.org definitions."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/13_schema_validator.ipynb.

# %% ../nbs/13_schema_validator.ipynb #c298bcb1
from __future__ import annotations
import json
import re
from typing import Any
import requests
from bs4 import BeautifulSoup

# %% auto #0
__all__ = ['GOOGLE_SPEC', 'GOOGLE_SUPPORTED_TYPES', 'fetch_html', 'extract_jsonld_schemas', 'extract_microdata_schemas',
           'extract_schemas', 'validate_schema', 'validate_page', 'validate_pages']

# %% ../nbs/13_schema_validator.ipynb #c3076428
# Google Rich Results spec: required and recommended fields per type
# Source: http://developers.google.com/search/docs/appearance/structured-data/search-gallery
GOOGLE_SPEC: dict[str, dict[str, list[str]]] = {
    "Article": {
        "required": ["@type", "headline", "image", "datePublished", "author"],
        "recommended": ["dateModified", "author.@type", "author.name", "publisher", "publisher.@type",
                        "publisher.name"],
    },
    "NewsArticle": {
        "required": ["@type", "headline", "image", "datePublished", "author"],
        "recommended": ["dateModified", "author.name", "publisher", "publisher.name"],
    },
    "BlogPosting": {
        "required": ["@type", "headline", "image", "datePublished", "author"],
        "recommended": ["dateModified", "author.name", "publisher", "publisher.name"],
    },
    "BreadcrumbList": {
        "required": ["@type", "itemListElement"],
        "recommended": ["itemListElement.@type", "itemListElement.position", "itemListElement.name",
                        "itemListElement.item"],
    },
    "Course": {
        "required": ["@type", "name", "description", "provider"],
        "recommended": ["provider.@type", "provider.name", "url", "hasCourseInstance"],
    },
    "Dataset": {
        "required": ["@type", "name", "description"],
        "recommended": ["url", "sameAs", "keywords", "creator", "license", "temporalCoverage", "spatialCoverage"],
    },
    "DiscussionForumPosting": {
        "required": ["@type", "headline", "url", "author"],
        "recommended": ["datePublished", "text", "author.name"],
    },
    "EmployerAggregateRating": {
        "required": ["@type", "itemReviewed", "ratingValue", "bestRating", "worstRating", "ratingCount"],
        "recommended": ["itemReviewed.name", "itemReviewed.sameAs"],
    },
    "Event": {
        "required": ["@type", "name", "startDate", "location"],
        "recommended": ["endDate", "description", "image", "organizer", "performer", "eventStatus",
                        "eventAttendanceMode", "offers"],
    },
    "FAQPage": {
        "required": ["@type", "mainEntity"],
        "recommended": ["mainEntity.@type", "mainEntity.name", "mainEntity.acceptedAnswer",
                        "mainEntity.acceptedAnswer.text"],
    },
    "ImageObject": {
        "required": ["@type", "contentUrl"],
        "recommended": ["license", "acquireLicensePage", "creditText", "creator", "copyrightNotice"],
    },
    "JobPosting": {
        "required": ["@type", "title", "description", "hiringOrganization", "jobLocation", "datePosted"],
        "recommended": ["validThrough", "employmentType", "baseSalary", "hiringOrganization.name",
                        "hiringOrganization.sameAs"],
    },
    "LocalBusiness": {
        "required": ["@type", "name", "address"],
        "recommended": ["address.@type", "address.streetAddress", "address.addressLocality", "address.addressCountry",
                        "telephone", "url", "openingHours", "geo", "priceRange", "image"],
    },
    "MathSolver": {
        "required": ["@type", "name", "potentialAction"],
        "recommended": ["potentialAction.@type", "potentialAction.mathExpression"],
    },
    "Movie": {
        "required": ["@type", "name"],
        "recommended": ["url", "image", "director", "dateCreated", "genre", "description", "aggregateRating"],
    },
    "Organization": {
        "required": ["@type", "name", "url", "logo"],
        "recommended": ["contactPoint", "sameAs", "address", "telephone", "foundingDate", "numberOfEmployees"],
    },
    "Product": {
        "required": ["@type", "name"],
        "recommended": ["image", "description", "sku", "brand", "offers", "aggregateRating", "review"],
    },
    "ProfilePage": {
        "required": ["@type", "mainEntity"],
        "recommended": ["mainEntity.@type", "mainEntity.name", "mainEntity.description", "mainEntity.image"],
    },
    "QAPage": {
        "required": ["@type", "mainEntity"],
        "recommended": ["mainEntity.@type", "mainEntity.name", "mainEntity.acceptedAnswer",
                        "mainEntity.suggestedAnswer"],
    },
    "Recipe": {
        "required": ["@type", "name", "image", "author", "datePublished", "description", "recipeIngredient",
                     "recipeInstructions"],
        "recommended": ["prepTime", "cookTime", "totalTime", "recipeYield", "nutrition", "aggregateRating", "video"],
    },
    "Review": {
        "required": ["@type", "itemReviewed", "reviewRating", "author"],
        "recommended": ["reviewRating.ratingValue", "reviewRating.bestRating", "author.name", "reviewBody",
                        "publisher"],
    },
    "AggregateRating": {
        "required": ["@type", "ratingValue", "reviewCount"],
        "recommended": ["bestRating", "worstRating", "itemReviewed"],
    },
    "SoftwareApplication": {
        "required": ["@type", "name", "operatingSystem", "applicationCategory"],
        "recommended": ["offers", "aggregateRating", "offers.price", "offers.priceCurrency"],
    },
    "SpeakableSpecification": {
        "required": ["@type", "cssSelector"],
        "recommended": ["xpath"],
    },
    "VacationRental": {
        "required": ["@type", "name", "description", "url"],
        "recommended": ["image", "address", "geo", "telephone", "aggregateRating", "numberOfRooms"],
    },
    "VideoObject": {
        "required": ["@type", "name", "description", "thumbnailUrl", "uploadDate"],
        "recommended": ["duration", "contentUrl", "embedUrl", "expires", "hasPart", "watchAction", "publication"],
    },
    "WebPage": {
        "required": ["@type", "name"],
        "recommended": ["url", "description", "breadcrumb", "lastReviewed"],
    },
    "WebSite": {
        "required": ["@type", "url"],
        "recommended": ["name", "potentialAction", "potentialAction.@type", "potentialAction.target",
                        "potentialAction.query-input"],
    },
    "Person": {
        "required": ["@type", "name"],
        "recommended": ["url", "image", "jobTitle", "worksFor", "sameAs"],
    },
    "ItemList": {
        "required": ["@type", "itemListElement"],
        "recommended": ["itemListElement.@type", "itemListElement.position", "itemListElement.url"],
    },
}

GOOGLE_SUPPORTED_TYPES: set[str] = set(GOOGLE_SPEC.keys())

# %% ../nbs/13_schema_validator.ipynb #151a03a3
import httpx


def fetch_html(url: str,  # URL to fetch
               timeout: int = 10  # Request timeout in seconds
               ) -> tuple[str, int]:
    "Fetch raw HTML from a live URL. Returns (html, status_code)."
    try:
        resp = httpx.get(url, headers={"User-Agent": "Mozilla/5.0 (compatible; seo-rat-schema-validator/1.0)"},
                         timeout=timeout)
        return resp.text, resp.status_code
    except httpx.RequestError:
        return "", 0


# %% ../nbs/13_schema_validator.ipynb #b0c0c060
def _get_nested(obj: dict,  # Schema dict to traverse
                dotpath: str  # Dot-notated field path e.g. 'author.name'
                ) -> Any:
    "Get a value from a nested dict using dot notation, handling lists by checking first element."
    current = obj
    for part in dotpath.split("."):
        if isinstance(current, list): current = current[0] if current else None
        if not isinstance(current, dict): return None
        current = current.get(part)
    return current


def _field_present(schema: dict,  # Schema dict
                   field: str  # Field name or dot-notated path
                   ) -> bool:
    "Check if a field is present and non-empty in a schema dict."
    val = _get_nested(schema, field)
    return bool(val) if val is not None else False


def extract_jsonld_schemas(html: str) -> list[dict]:
    """Extract all JSON-LD schema blocks from HTML. Returns list of parsed dicts."""
    soup = BeautifulSoup(html, "html.parser")
    schemas = []
    for tag in soup.find_all("script", type="application/ld+json"):
        try:
            data = json.loads(tag.string or "")
            # Handle @graph arrays
            if isinstance(data, dict) and "@graph" in data:
                for item in data["@graph"]:
                    schemas.append({"format": "json-ld", "raw": item})
            elif isinstance(data, list):
                for item in data:
                    schemas.append({"format": "json-ld", "raw": item})
            elif isinstance(data, dict):
                schemas.append({"format": "json-ld", "raw": data})
        except (json.JSONDecodeError, TypeError):
            continue
    return schemas


def extract_microdata_schemas(html: str  # Raw HTML content
                              ) -> list[dict]:
    "Extract Microdata itemscope blocks from HTML as flat dicts."
    soup = BeautifulSoup(html, "html.parser")
    schemas = []
    for item in soup.find_all(attrs={"itemscope": True, "itemtype": True}):
        itemtype = item.get("itemtype", "")
        raw = {"@type": itemtype.split("/")[-1] if itemtype else ""}
        for prop in item.find_all(attrs={"itemprop": True}):
            if name := prop.get("itemprop"):
                raw[name] = (prop.get("content") or
                             prop.get("href") or
                             prop.get_text(strip=True))
        schemas.append({"format": "microdata", "raw": raw})
    return schemas


def extract_schemas(html: str) -> list[dict]:
    """Extract all schema blocks (JSON-LD + Microdata) from HTML."""
    return extract_jsonld_schemas(html) + extract_microdata_schemas(html)

# %% ../nbs/13_schema_validator.ipynb #1dc25b04
def validate_schema(schema_block: dict  # Dict with 'format' and 'raw' keys
                    ) -> dict:
    "Validate a single schema block against Google's rich result spec."
    raw = schema_block.get("raw", {})
    fmt = schema_block.get("format", "unknown")

    raw_type = raw.get("@type", "")
    if isinstance(raw_type, list): raw_type = next(iter(raw_type), "")
    schema_type = raw_type.replace("https://schema.org/", "").replace("http://schema.org/", "")

    google_supported = schema_type in GOOGLE_SUPPORTED_TYPES
    spec = GOOGLE_SPEC.get(schema_type, {"required": [], "recommended": []})

    missing_required = [f for f in spec["required"] if not _field_present(raw, f)]
    missing_recommended = [f for f in spec["recommended"] if not _field_present(raw, f)]
    fields_present = [f for f in spec["required"] + spec["recommended"] if _field_present(raw, f)]

    warning_checks = [
        (not schema_type,
         "@type is missing — Google cannot identify this schema"),
        (not google_supported and schema_type,
         f"'{schema_type}' is not a Google rich result type — no rich snippet will be generated"),
        (isinstance(raw.get("image"), str) and schema_type in ("Article", "Recipe", "VideoObject"),
         "'image' should be an ImageObject or array, not a bare string"),
        (schema_type == "Article" and isinstance(raw.get("author"), str),
         "'author' should be a Person or Organization object, not a bare string"),
        (schema_type == "LocalBusiness" and not raw.get("@id"),
         "'@id' is missing — recommended for LocalBusiness to enable knowledge panel"),
        (schema_type == "FAQPage" and isinstance(raw.get("mainEntity"), list) and not raw.get("mainEntity"),
         "'mainEntity' is empty — FAQPage needs at least one Question"),
    ]
    warnings = [msg for condition, msg in warning_checks if condition]

    return {"format": fmt, "type": schema_type or "(unknown)",
            "google_supported": google_supported,
            "is_valid": not missing_required and bool(schema_type),
            "all_fields_in_raw": list(raw.keys()),
            "fields_present_from_spec": fields_present,
            "fields_missing_required": missing_required,
            "fields_missing_recommended": missing_recommended,
            "warnings": warnings, "raw": raw}


# %% ../nbs/13_schema_validator.ipynb #3268c345
def validate_page(url: str,  # Live page URL to validate
                  timeout: int = 10  # HTTP request timeout in seconds
                  ) -> dict:
    "Fetch a live URL and validate all schema.org markup found on the page."
    html, status = fetch_html(url, timeout=timeout)
    if not html:
        return {"url": url, "fetch_status": status, "error": "Failed to fetch page",
                "schemas_found": [],
                "summary": {"total_schemas": 0, "valid_count": 0, "types_found": [], "has_google_supported": False}}
    validated = [validate_schema(s) for s in extract_schemas(html)]
    return {"url": url, "fetch_status": status, "schemas_found": validated,
            "summary": {"total_schemas": len(validated),
                        "valid_count": sum(1 for v in validated if v["is_valid"]),
                        "types_found": [v["type"] for v in validated],
                        "has_google_supported": any(v["google_supported"] for v in validated)}}

# %% ../nbs/13_schema_validator.ipynb #2820c15e
def validate_pages(urls: list[str],  # List of page URLs to validate
                   timeout: int = 10  # HTTP request timeout in seconds
                   ) -> list[dict]:
    "Validate schema markup for a list of URLs."
    return [validate_page(url, timeout=timeout) for url in urls]
