"""Sync articles, detect duplicate metadata, and generate SEO reports from GSC data."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_seo_report.ipynb.

# %% auto #0
__all__ = ['FETCH', 'sync_articles_to_db', 'find_duplicate_metadata', 'analyze_links', 'check_heading_structure',
           'analyze_article', 'generate_seo_report', 'print_issues_report']

# %% ../nbs/09_seo_report.ipynb #55e2ad2b
from sqlmodel import Session, select
from .article import get_article_by_path, insert_article, Article
from .sqlite_db import get_session
from .models import Website
from .content_mapper import map_all_urls_to_files, fetch_sitemap_urls
from seo_rat.content_parser import (
    parse_metadata,
    parse_notebook_metadata,
    remove_metadata,
    extract_headers,
    extract_images,
    extract_links,
    filter_external_links,
    filter_internal_links,
    check_desc_length,
    check_content_length,
    check_title_length,
    imgs_missing_alts,
    extract_notebook_content, extract_html_metadata, fetch_url_as_markdown,
)
from .seo_content_analysis import check_h1_count, check_keyword_placement
from .gsc_insights import detect_query_trends, classify_page_intents, find_green_keywords
import httpx

FETCH = "::fetch::"



# %% ../nbs/09_seo_report.ipynb #fb2feeae
def sync_articles_to_db(session: Session,  # Active database session
                        website_id: int,  # Parent website ID
                        url_file_mapping: dict[str, str]  # URL → file path mapping
                        ) -> None:
    "Insert articles into the database, skipping already existing ones."
    for url, file_path in url_file_mapping.items():
        if not file_path: continue
        if file_path == FETCH:
            existing = session.exec(select(Article).where(Article.url == url)).first()
        else:
            existing = get_article_by_path(session, file_path)
        if not existing:
            insert_article(session, Article(website_id=website_id, file_path=file_path, url=url))


# %% ../nbs/09_seo_report.ipynb #24bd6d69
def _collect_metadata_field(session: Session,  # Active database session
                            website_id: int,  # Parent website ID
                            field: str  # Metadata field to extract
                            ) -> dict[str, str]:
    "Collect metadata field values from all articles in a website."
    from seo_rat.content_parser import parse_metadata, parse_notebook_metadata
    values = {}
    for article in get_articles_by_website(session, website_id):
        if article.file_path == FETCH:
            continue
        content = open(article.file_path).read()
        meta = parse_notebook_metadata(content) if article.file_path.endswith(".ipynb") else parse_metadata(content)
        values[article.file_path] = meta.get(field, "")
    return values


def find_duplicate_metadata(session: Session,  # Active database session
                            field: str,  # Metadata field to check
                            website_id: int,  # Parent website ID
                            similarity_threshold: float = 0.9  # Minimum similarity to flag
                            ) -> list[dict]:
    "Find articles with duplicate or very similar metadata field values."
    from seo_rat.content_parser import calculate_similarity
    values = _collect_metadata_field(session, website_id, field)
    duplicates = []
    checked = set()
    for path1, field1 in values.items():
        for path2, field2 in values.items():
            if path1 >= path2 or (path1, path2) in checked: continue
            if not field1 or not field2: continue
            if (similarity := calculate_similarity(field1, field2)) >= similarity_threshold:
                duplicates.append({"file1": path1, "file2": path2,
                                   f"{field}_1": field1, f"{field}_2": field2,
                                   "similarity": similarity})
            checked.add((path1, path2))
    return duplicates

# %% ../nbs/09_seo_report.ipynb #06c02666
from .gsc_storage import get_top_queries
from .article import get_articles_by_website
from .gsc_client import get_date_range
from .seo_content_analysis import check_keyword_placement, content_freshness
from .gsc_insights import find_missing_queries

# %% ../nbs/09_seo_report.ipynb #69064449
def analyze_links(content: str,  # Page content
                  domain: str  # Site domain to classify links
                  ) -> dict:
    "Analyze internal and external links in content."
    all_urls = list(extract_links(content).keys())
    return {"total_links": len(all_urls),
            "internal_count": len(filter_internal_links(all_urls, domain)),
            "external_count": len(filter_external_links(all_urls, domain)),
            "internal_links": filter_internal_links(all_urls, domain),
            "external_links": filter_external_links(all_urls, domain)}


# %% ../nbs/09_seo_report.ipynb #533e76c22228125d
def check_heading_structure(headers: list[dict]  # Headers from `extract_headers`
                            ) -> dict:
    "Check heading structure for H2 presence and skipped levels."
    levels = [int(h["type"][1]) for h in headers]
    skipped = [{"from": headers[i], "to": headers[i + 1]}
               for i in range(len(levels) - 1) if levels[i + 1] - levels[i] > 1]
    return {"has_h2": any(h["type"] == "h2" for h in headers), "skipped_levels": skipped}


# %% ../nbs/09_seo_report.ipynb #24b0b9a4
def analyze_article(article: Article,
                    domain: str,
                    is_quarto: bool,
                    title_is_h1: bool = False,
                    desc_field: str = "description",
                    title_field: str = "title",
                    date_field: str = "date",
                    fetch_base_url: str | None = None  # ADD
                    ) -> dict:
    if article.file_path == FETCH:
        fetch_url = article.url.replace(f"https://{domain}", fetch_base_url) if fetch_base_url else article.url
        html = httpx.get(fetch_url).text  # FIX: use fetch_url
        metadata = extract_html_metadata(html)
        content = fetch_url_as_markdown(fetch_url)
        headers = extract_headers(content)
    elif article.file_path.endswith(".ipynb"):
        raw = open(article.file_path).read()
        metadata = parse_notebook_metadata(raw)
        content = extract_notebook_content(raw, is_quarto=is_quarto)
        headers = extract_headers(content)
    else:
        raw = open(article.file_path).read()
        metadata = parse_metadata(raw)
        content = remove_metadata(raw)
        headers = extract_headers(content)

    return {"file_path": article.file_path,
            "title_check": check_title_length(metadata.get(title_field, "")),
            "description_check": check_desc_length(metadata.get(desc_field, "")),
            "content_check": check_content_length(content),
            "h1_check": check_h1_count(headers, title=metadata.get("title", ""), title_is_h1=title_is_h1),
            "missing_alts": imgs_missing_alts(extract_images(content)),
            "link_analysis": analyze_links(content, domain),
            "keyword_placement": check_keyword_placement(article.focus_keyword, metadata=metadata,
                                                         headers=headers, content=content, url=article.url,
                                                         desc_field=desc_field, title_is_h1=title_is_h1),
            "content_freshness": content_freshness(metadata.get(date_field, "")),
            "content_structure": check_heading_structure(headers)}


# %% ../nbs/09_seo_report.ipynb #a1e0e1e8
def _collect_page_issues(
        report: dict,  # Result from `analyze_article`
        article: Article,  # Article being analyzed
) -> list[str]:
    "Collect all SEO issues from an article report as a list of strings."
    issues = []
    if not report["h1_check"]["has_single_h1"]:
        issues.append("Multiple or no H1")
    if not report["content_check"]["is_sufficient"]:
        issues.append("Content too short")
    if report["link_analysis"]["internal_count"] == 0:
        issues.append("No internal links, at least 3 recommended")
    if report["link_analysis"]["external_count"] == 0:
        issues.append("No external links")
    if report["missing_alts"]:
        issues.append(f"Images missing alt text ({len(report['missing_alts'])})")
    if not report["content_structure"]["has_h2"]:
        issues.append("No H2 headings, at least one recommended")
    for skip in report["content_structure"]["skipped_levels"]:
        issues.append(
            f"Skipped heading: {skip['from']['type']} → {skip['to']['type']} (line {skip['to']['line_number']})"
        )
    tc = report["title_check"]
    if tc["status"] != "optimal":
        issues.append(
            f"Title {tc['status']} ({tc['length']} chars, range {tc['min']}-{tc['max']})"
        )
    dc = report["description_check"]
    if dc["status"] != "optimal":
        issues.append(
            f"Description {dc['status']} ({dc['length']} chars, range {dc['min']}-{dc['max']})"
        )
    if not report["content_freshness"]["is_fresh"]:
        issues.append(
            f"Stale content ({report['content_freshness']['days_since_update']} days old)"
        )
    if article.focus_keyword:
        if not report["keyword_placement"]["in_h1"]:
            issues.append("Focus keyword not in H1")
        if not report["keyword_placement"]["keyword_in_meta"]["in_description"]:
            issues.append("Focus keyword not in description")
        if not report["keyword_placement"]["keyword_in_meta"]["in_title"]:
            issues.append("Focus keyword not in title")
        if not report["keyword_placement"]["keyword_at_first"]:
            issues.append("Focus keyword not in first 100 words")
    return issues


def generate_seo_report(
        session: Session,
        website_id: int,
        domain: str,
        is_quarto: bool,
        title_is_h1: bool = False,
        desc_field: str = "description",
        title_field: str = "title",
        date_field: str = "date",
        include_insights: bool = False,  # Include query intents, trends, green keywords
        days: int = 90,  # Days for insights lookback
        query_limit: int = 100,  # Max queries for insights
        fetch_base_url: str | None = None,
) -> dict:
    "Generate a comprehensive SEO report for all articles in a website."
    articles = get_articles_by_website(session, website_id)
    start, end = get_date_range("last_days", days=90 * 8)
    page_reports, issues = [], {}

    for article in articles:
        try:
            report = analyze_article(
                article,
                domain,
                is_quarto,
                title_is_h1=title_is_h1,
                desc_field=desc_field,
                title_field=title_field,
                date_field=date_field,
                fetch_base_url=fetch_base_url,
            )
            queries = get_top_queries(
                session=session,
                site_url=f"sc-domain:{domain}",
                start_date=start,
                end_date=end,
                page_path=article.url.removeprefix(f"https://{domain}/"),
                limit=500,
                sort_by="impressions",
            )
            if article.file_path == FETCH:
                content = fetch_url_as_markdown(
                    article.url.replace(f"https://{domain}", fetch_base_url)
                    if fetch_base_url
                    else article.url
                )
            else:
                content = remove_metadata(open(article.file_path).read())
            missing_queries = find_missing_queries(queries=queries, content=content)

            missing_queries = find_missing_queries(queries=queries, content=content)
            page_issues = _collect_page_issues(report, article)

            if include_insights:
                page_path = article.url.removeprefix(f"https://{domain}/")
                insight_start, insight_end = get_date_range("last_days", days=days)
                trends = detect_query_trends(
                    session,
                    f"sc-domain:{domain}",
                    page_path=page_path,
                    days=days,
                    limit=query_limit,
                )
                report["query_intents"] = classify_page_intents(
                    session,
                    f"sc-domain:{domain}",
                    insight_start,
                    insight_end,
                    page_path=page_path,
                    limit=query_limit,
                )
                report["trends"] = {
                    "rising": [t for t in trends if t["trend"] == "rising"],
                    "declining": [t for t in trends if t["trend"] == "declining"],
                }
                report["green_keywords"] = find_green_keywords(
                    session, f"sc-domain:{domain}", page_path, content, days=days
                )

            if page_issues or missing_queries:
                issues[article.url or article.file_path] = {
                    "file_path": article.file_path,
                    "issues": page_issues,
                    "data": {
                        "missing_queries": missing_queries,
                        "keyword_placement": report.get("keyword_placement", {}),
                    },
                }
            page_reports.append(report)
        except Exception as e:
            print(f"Error analyzing {article.file_path}: {e}")

    duplicate_titles = find_duplicate_metadata(session, "title", website_id)
    duplicate_descriptions = find_duplicate_metadata(session, "description", website_id)

    return {
        "total_pages": len(articles),
        "pages_analyzed": len(page_reports),
        "page_reports": page_reports,
        "duplicate_titles": duplicate_titles,
        "duplicate_descriptions": duplicate_descriptions,
        "issues": issues,
        "summary": {
            "total_issues": sum(len(v["issues"]) for v in issues.values()),
            "pages_with_issues": len(issues),
            "duplicate_titles_count": len(duplicate_titles),
            "duplicate_descriptions_count": len(duplicate_descriptions),
        },
    }


# %% ../nbs/09_seo_report.ipynb #487b7796
def print_issues_report(report: dict  # Result from `generate_seo_report`
                        ) -> None:
    "Print SEO issues sorted from most issues to fewest."
    issues, summary = report["issues"], report["summary"]
    print(f"Pages analysed   : {report['pages_analyzed']} / {report['total_pages']}")
    print(f"Pages with issues: {summary['pages_with_issues']}")
    print(f"Total issue count: {summary['total_issues']}")
    print(f"Duplicate titles : {summary['duplicate_titles_count']}")
    print(f"Duplicate descs  : {summary['duplicate_descriptions_count']}")
    print("=" * 70)
    for url, data in sorted(issues.items(), key=lambda x: len(x[1]["issues"]), reverse=True):
        count = len(data["issues"])
        print(f"\n[{count} issue{'s' if count != 1 else ''}] {url}")
        for i, issue in enumerate(data["issues"], 1): print(f"  {i}. {issue}")
        if missing := data.get("data", {}).get("missing_queries", []):
            print(f"  Missing queries ({len(missing)}):")
            for q in missing:
                print(
                    f"      - {q['query']} (clicks: {q['total_clicks']}, impressions: {q['total_impressions']}, pos: {q['avg_position']:.1f})")

