"""Analyze content for keyword placement, heading structure, and on-page SEO factors."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_seo_content_analysis.ipynb.

# %% auto #0
__all__ = ['calculate_keyword_density', 'find_cannibalized', 'check_h1_count', 'keyword_in_first_section',
           'check_paragraph_length', 'keyword_in_metadata', 'keyword_in_alt_texts', 'analyze_header_distribution',
           'check_keyword_placement', 'content_freshness']

# %% ../nbs/10_seo_content_analysis.ipynb #9b955c78
def calculate_keyword_density(content: str,  # Page content
                              keyword: str  # Keyword to search for
                              ) -> dict:
    "Calculate keyword density using word-level matching."
    content_words = content.lower().split()
    keyword_words = keyword.lower().split()
    n = len(keyword_words)
    positions = [i for i in range(len(content_words) - n + 1)
                 if content_words[i:i + n] == keyword_words]
    total = len(content_words)
    return {"keyword": keyword, "count": len(positions),
            "density": (len(positions) / total * 100) if total > 0 else 0,
            "positions": positions}



# %% ../nbs/10_seo_content_analysis.ipynb #a9a04575619ac96c
from .article import get_articles_by_website
from .content_parser import get_page_content
from .sqlite_db import get_session
from .models import GSCAnalytics
from .gsc_insights import get_top_queries
from .gsc_client import get_date_range
from sqlmodel import select


# %% ../nbs/10_seo_content_analysis.ipynb #8157f3d628982cbe
def find_cannibalized(session,  # Active database session
                      website_id: int,  # Website ID
                      site_url: str,  # GSC property URL
                      start: str,  # Start date (YYYY-MM-DD)
                      end: str  # End date (YYYY-MM-DD)
                      ) -> dict:
    "Find keyword cannibalization via exact focus keyword matches and GSC ranking data."
    from collections import defaultdict
    articles = get_articles_by_website(session=session, website_id=website_id)
    kw_map = defaultdict(list)
    for a in articles:
        if a.focus_keyword: kw_map[a.focus_keyword].append(a.url)
    exact_matches = [{"keyword": kw, "pages": urls}
                     for kw, urls in kw_map.items() if len(urls) >= 2]
    gsc_matches = []
    for query in [r["query"] for r in get_top_queries(session, site_url, start, end, limit=1000)]:
        pages = session.exec(
            select(GSCAnalytics.page).where(
                GSCAnalytics.site_url == site_url, GSCAnalytics.query == query,
                GSCAnalytics.date.between(start, end), GSCAnalytics.position <= 20,
            ).distinct()
        ).all()
        if len(pages) >= 2: gsc_matches.append({"query": query, "pages": pages})
    return {"exact_matches": exact_matches, "gsc_matches": gsc_matches}

# %% ../nbs/10_seo_content_analysis.ipynb #41378f3c
def check_h1_count(headers: list[dict],  # Headers from `extract_headers`
                   title: str | None = None,  # Frontmatter title (for Quarto)
                   title_is_h1: bool = False  # Whether title counts as H1
                   ) -> dict:
    "Check H1 count — for Quarto, the title frontmatter field acts as H1."
    if title_is_h1 and title: return {"h1_count": 1, "has_single_h1": True, "h1_source": "title"}
    h1s = [h for h in headers if h["type"] == "h1"]
    return {"h1_count": len(h1s), "has_single_h1": len(h1s) == 1}

# %% ../nbs/10_seo_content_analysis.ipynb #c1209cfb
def keyword_in_first_section(content: str,  # Page content
                             keyword: str,  # Keyword to search for
                             percent: int = 10  # Percentage of content to check
                             ) -> bool:
    "Check if keyword appears in the first X% of content."
    return keyword.lower() in content[:int(len(content) * percent / 100)].lower()

# %% ../nbs/10_seo_content_analysis.ipynb #8d3eded2
def check_paragraph_length(content: str  # Page content
                           ) -> dict:
    "Check average number of sentences per paragraph."
    paragraphs = [p.strip() for p in content.split("\n\n") if p.strip()]
    avg = sum(len(p.split(". ")) for p in paragraphs) / len(paragraphs) if paragraphs else 0
    return {"avg_sentences_per_paragraph": avg, "is_optimal": 2 <= avg <= 4}

# %% ../nbs/10_seo_content_analysis.ipynb #445edd7d
def keyword_in_metadata(metadata: dict,  # Parsed frontmatter dict
                        keyword: str,  # Keyword to search for
                        desc_field: str = "description"  # Frontmatter description field
                        ) -> dict:
    "Check if keyword appears in title and description metadata fields."
    kw = keyword.lower()
    return {"in_title": kw in str(metadata.get("title", "")).lower(),
            "in_description": kw in str(metadata.get(desc_field, "")).lower()}

# %% ../nbs/10_seo_content_analysis.ipynb #24b7c979
def keyword_in_alt_texts(images: list[dict],  # Images from `extract_images`
                         keyword: str  # Keyword to search for
                         ) -> bool:
    "Check if keyword appears in any image alt text."
    return any(keyword.lower() in img.get("alt_text", "").lower() for img in images)

# %% ../nbs/10_seo_content_analysis.ipynb #a0d712ef
def analyze_header_distribution(headers: list[dict]  # Headers from `extract_headers`
                                ) -> dict:
    "Analyze header type distribution as counts and percentages."
    from collections import Counter
    counts = dict(Counter(h["type"] for h in headers))
    total = len(headers)
    return {"counts": counts,
            "percentages": {k: (v / total * 100) if total > 0 else 0 for k, v in counts.items()}}


# %% ../nbs/10_seo_content_analysis.ipynb #81cdf15b
def check_keyword_placement(keyword: str | None,  # Focus keyword
                            metadata: dict,  # Parsed frontmatter dict
                            headers: list[dict],  # Headers from `extract_headers`
                            content: str,  # Page content
                            url: str,  # Page URL
                            desc_field: str = "description",  # Frontmatter description field
                            title_is_h1: bool = False  # Whether title counts as H1
                            ) -> dict:
    "Check where the focus keyword appears across page elements."
    if not keyword:
        return {"in_h1": False, "in_url": False,
                "keyword_in_meta": {"in_title": False, "in_description": False},
                "keyword_at_first": False}
    in_h1 = any(keyword.lower() in h["content"].lower() for h in headers if h["type"] == "h1")
    if title_is_h1: in_h1 = in_h1 or keyword.lower() in str(metadata.get("title", "")).lower()
    return {"in_h1": in_h1, "in_url": keyword.lower() in url.lower(),
            "keyword_in_meta": keyword_in_metadata(metadata, keyword, desc_field=desc_field),
            "keyword_at_first": keyword_in_first_section(content, keyword)}

# %% ../nbs/10_seo_content_analysis.ipynb #f1c9ac58
def content_freshness(last_updated: str,  # Last updated date (YYYY-MM-DD)
                      days: int = 180  # Max days to consider content fresh
                      ) -> dict:
    "Check content freshness based on last updated date."
    from datetime import datetime
    try:
        updated = datetime.fromisoformat(str(last_updated))
        delta = (datetime.now() - updated).days
        return {"last_updated": last_updated, "days_since_update": delta, "is_fresh": delta <= days}
    except (ValueError, TypeError):
        return {"last_updated": last_updated, "days_since_update": None, "is_fresh": True}

