"""Crawl and analyze entire sites for technical SEO issues and link structure."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_seo_site_analysis.ipynb.

# %% auto #0
__all__ = ['detect_duplicate_content', 'analyze_keyword_cannibalization', 'analyze_content_groups', 'get_shingles',
           'minhash_signature', 'minhash_similarity', 'analyze_content_groups_fast']

# %% ../nbs/11_seo_site_analysis.ipynb #78c004a8
from sqlmodel import Session, select
from .article import Article,get_articles_by_website
from .content_parser import remove_metadata, normalize_text, calculate_similarity
from .seo_content_analysis import calculate_keyword_density

# %% ../nbs/11_seo_site_analysis.ipynb #adebe122
def detect_duplicate_content(session:Session,              # Active database session
                              website_id:int,               # Website to search within
                              content:str,                  # Normalized page content
                              file_path:str,                # Current article path (to exclude self)
                              similarity_threshold:float=0.8 # Minimum similarity to flag
                             ) -> dict:
    "Find articles within a website with content similar to the given content."
    current = normalize_text(remove_metadata(content))
    similar = []
    for article in get_articles_by_website(session, website_id):
        if article.file_path == file_path: continue
        other = normalize_text(remove_metadata(open(article.file_path).read()))
        if (sim := calculate_similarity(current, other)) >= similarity_threshold:
            similar.append({"file_path": article.file_path, "similarity": sim})
    return {"has_duplicates": len(similar) > 0, "similar_articles": similar}


# %% ../nbs/11_seo_site_analysis.ipynb #ead01c83
def analyze_keyword_cannibalization(session:Session, # Active database session
                                    website_id:int,  # Website to search within
                                    keyword:str      # Focus keyword to check
                                   ) -> dict:
    "Find articles within a website competing for the same focus keyword."
    articles = [a for a in get_articles_by_website(session, website_id)
                if a.focus_keyword == keyword]
    if len(articles) <= 1:
        return {"has_cannibalization": False, "keyword": keyword, "count": len(articles)}
    results = [{"file_path": a.file_path,
                **{k: v for k, v in calculate_keyword_density(
                    remove_metadata(open(a.file_path).read()), keyword).items()
                   if k in ("density", "count")}}
               for a in articles]
    return {"has_cannibalization": True, "keyword": keyword,
            "count": len(articles), "articles": results}


def analyze_content_groups(session:Session,              # Active database session
                           website_id:int,               # Website to search within
                           similarity_threshold:float=0.8 # Minimum similarity to group
                          ) -> dict:
    "Group similar articles together across a website."
    articles = get_articles_by_website(session, website_id)
    groups, processed = [], set()
    for article in articles:
        if article.id in processed: continue
        main = normalize_text(remove_metadata(open(article.file_path).read()))
        group = {"main_article": article.file_path, "similar_articles": []}
        for other in articles:
            if other.id == article.id or other.id in processed: continue
            other_content = normalize_text(remove_metadata(open(other.file_path).read()))
            if (sim := calculate_similarity(main, other_content)) >= similarity_threshold:
                group["similar_articles"].append({"file_path": other.file_path, "similarity": sim})
                processed.add(other.id)
        if group["similar_articles"]:
            groups.append(group)
            processed.add(article.id)
    return {"total_articles": len(articles), "groups": groups, "duplicate_groups": len(groups)}


# %% ../nbs/11_seo_site_analysis.ipynb #9e4e60af7b4cfe7e
import hashlib

def get_shingles(text: str, n: int = 3) -> set:
    "Generate n-word shingles from text."
    words = text.lower().split()
    return {" ".join(words[i:i+n]) for i in range(len(words) - n + 1)}

def minhash_signature(shingles: set, num_hashes: int = 128) -> list[int]:
    "Compute MinHash signature for a set of shingles."
    signature = []
    for seed in range(num_hashes):
        min_hash = min(
            int(hashlib.md5(f"{seed}:{s}".encode()).hexdigest(), 16)
            for s in shingles
        ) if shingles else 0
        signature.append(min_hash)
    return signature

def minhash_similarity(sig1: list[int], sig2: list[int]) -> float:
    "Estimate Jaccard similarity from two MinHash signatures."
    return sum(a == b for a, b in zip(sig1, sig2)) / len(sig1)

def analyze_content_groups_fast(session: Session, website_id: int,
                                 similarity_threshold: float = 0.8,
                                 num_hashes: int = 128) -> dict:
    "Group similar articles using MinHash for fast approximate similarity."
    articles = get_articles_by_website(session, website_id)
    sigs = {}
    for a in articles:
        try:
            text = remove_metadata(open(a.file_path).read())
            sigs[a.id] = (a.file_path, minhash_signature(get_shingles(text), num_hashes))
        except Exception:
            continue

    groups, processed = [], set()
    ids = list(sigs.keys())
    for i, id1 in enumerate(ids):
        if id1 in processed: continue
        path1, sig1 = sigs[id1]
        group = {"main_article": path1, "similar_articles": []}
        for id2 in ids[i+1:]:
            if id2 in processed: continue
            path2, sig2 = sigs[id2]
            sim = minhash_similarity(sig1, sig2)
            if sim >= similarity_threshold:
                group["similar_articles"].append({"file_path": path2, "similarity": sim})
                processed.add(id2)
        if group["similar_articles"]:
            groups.append(group)
            processed.add(id1)

    return {"total_articles": len(articles), "groups": groups, "duplicate_groups": len(groups)}

