"""A Simple API for configure the DB connection with Sqlite

Docs: https://abdelkareemkobo.github.io/seo_ratsqlite.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_sqlite.ipynb.

# %% auto #0
__all__ = ['get_session']

# %% ../nbs/00_sqlite.ipynb #96fa0d1b
from sqlmodel import create_engine, Session, SQLModel
import os
from dotenv import load_dotenv

load_dotenv()


# %% ../nbs/00_sqlite.ipynb #ed723feac521dba
from contextlib import contextmanager


@contextmanager
def get_session(db_url: str | None = None  # Full SQLite URL, or uses `SEO_RAT_DB_URL` env var
                ) -> Session:
    "Create a SQLite session."
    if db_url is None: db_url = os.getenv("SEO_RAT_DB_URL")
    engine = create_engine(db_url)
    SQLModel.metadata.create_all(engine)
    session = Session(engine)
    try:
        yield session
    finally:
        session.close()


