"""Functions for validating SEO-relevant content lengths for titles, descriptions, and body text.

Docs: https://abdelkareemkobo.github.io/seootterparser_checks.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02b_parser_checks.ipynb.

# %% auto #0
__all__ = ['check_length', 'check_title_length', 'check_desc_length', 'check_content_length']

# %% ../../nbs/02b_parser_checks.ipynb #bc3299d7e117e914
import re


# %% ../../nbs/02b_parser_checks.ipynb #41a3989d85f81776
def check_length(text: str,  # Text to check
                 min_len: int,  # Minimum optimal length
                 max_len: int  # Maximum optimal length
                 ) -> dict:
    "Check if text length falls within the optimal range."
    length = len(text)
    return {"length": length, "optimal_length": min_len <= length <= max_len}

def check_title_length(title: str,  # Page title to check
                       min_len: int = 30,  # Minimum optimal length
                       max_len: int = 70  # Maximum optimal length
                       ) -> dict:
    "Check if a page title length is optimal for SEO."
    length = len(title)
    if length < min_len:
        status = "too_short"
    elif length > max_len:
        status = "too_long"
    else:
        status = "optimal"
    return {"length": length, "status": status, "min": min_len, "max": max_len}

def check_desc_length(description: str,  # Meta description to check
                      min_len: int = 50,  # Minimum optimal length
                      max_len: int = 320  # Maximum optimal length
                      ) -> dict:
    "Check if a meta description length is optimal for SEO."
    length = len(description)
    if length == 0:
        status = "missing"
    elif length < min_len:
        status = "too_short"
    elif length > max_len:
        status = "too_long"
    else:
        status = "optimal"
    return {"length": length, "status": status, "min": min_len, "max": max_len}

def check_content_length(content: str  # Page body content
                         ) -> dict:
    "Check if page content has sufficient word count for SEO."
    words = len(content.split())
    return {"word_count": words, "is_sufficient": words >= 300}

