"""Functions for extracting headers, links, and images from markdown and HTML content.

Docs: https://abdelkareemkobo.github.io/seootterparser_extractors.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02c_parser_extractors.ipynb.

# %% auto #0
__all__ = ['IMAGE_EXTS', 'extract_headers', 'extract_links', 'extract_images', 'imgs_missing_alts', 'filter_internal_links',
           'filter_external_links']

# %% ../../nbs/02c_parser_extractors.ipynb #8de994ac0e367dbc
import re
from urllib.parse import urlparse
from .utils import is_special_url

IMAGE_EXTS = (".png", ".jpg", ".jpeg", ".gif", ".bmp", ".svg", ".webp")


# %% ../../nbs/02c_parser_extractors.ipynb #f0d3ee70d6ec9dc8
def extract_headers(content: str) -> list[dict]:
    "Extract all headers from markdown content."
    headings = []
    for line_number, line in enumerate(content.splitlines(), start=1):
        line = line.strip()
        for level in range(1, 7):
            prefix = "#" * level + " "
            if line.startswith(prefix):
                text = line.strip("#").strip()
                headings.append({"type": f"h{level}", "line_number": line_number,
                                 "content": text, "length": len(text)})
                break
    return headings


# %% ../../nbs/02c_parser_extractors.ipynb #1255494a98500a30
def extract_links(content: str) -> dict[str, dict]:
    """Extract all links with metadata"""
    links = {}
    lines = content.split("\n")
    for line_number, line in enumerate(lines, start=1):
        for match in re.finditer(r"(?<!!)\[(.*?)\]\((.*?)\)", line):
            title, url = match.groups()
            url = re.sub(r"""\s+["'].*?["']\s*$""", '', url).strip()
            if url not in links:
                links[url] = {"titles": [], "lines": []}
            links[url]["titles"].append(title)
            links[url]["lines"].append(line_number)

    # Also extract HTML links
    try:
        from bs4 import BeautifulSoup
    except Exception:
        return links

    soup = BeautifulSoup(content, "html.parser")
    for a in soup.find_all("a", href=True):
        url = a.get("href", "").strip()
        if not url:
            continue
        title = a.get_text(strip=True)
        if url not in links:
            links[url] = {"titles": [], "lines": []}
        links[url]["titles"].append(title)
        links[url]["lines"].append(-1)  # HTML line unknown
    return links


# %% ../../nbs/02c_parser_extractors.ipynb #8ffd90a2cf4e5b6
def extract_images(content: str  # Markdown or HTML content
                   ) -> list[dict]:
    "Extract images with alt text from markdown and HTML."
    images = [{"alt_text": alt, "url": url} for alt, url in re.findall(r"\!\[(.*?)\]\((.*?)\)", content)]
    try:
        from bs4 import BeautifulSoup
        for img in BeautifulSoup(content, "html.parser").find_all("img"):
            if src := img.get("src", "").strip():
                images.append({"alt_text": img.get("alt", "").strip(), "url": src})
    except Exception:
        pass
    return images


# %% ../../nbs/02c_parser_extractors.ipynb #5111d76b6578c95a
def imgs_missing_alts(images: list[dict]  # List of image dicts from `extract_images`
                      ) -> list[str]:
    "Return URLs of images missing alt text."
    return [img["url"] for img in images if not img.get("alt_text")]


# %% ../../nbs/02c_parser_extractors.ipynb #288f799aa14fce9c
def filter_internal_links(urls: list[str],  # List of URLs to filter
                          domain: str  # Domain to match against (e.g. 'example.com')
                          ) -> list[str]:
    "Filter for internal links, excluding images and special URLs."
    return [u for u in urls if not is_special_url(u)
            and not u.lower().endswith(IMAGE_EXTS)
            and (not u.startswith("http") or urlparse(u).netloc == domain)]


# %% ../../nbs/02c_parser_extractors.ipynb #2fb7e7ed2855cbb
def filter_external_links(urls: list[str],  # List of URLs to filter
                          domain: str  # Site domain to exclude
                          ) -> list[str]:
    "Filter for external links only, excluding images and special URLs."
    internal = filter_internal_links(urls, domain)
    return [u for u in urls if u not in internal
            and not u.lower().endswith(IMAGE_EXTS)
            and not is_special_url(u)]
