"""Classify query intent based on keyword patterns.

Docs: https://abdelkareemkobo.github.io/seo_ratinsights_intent.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/12b_insights_intent.ipynb.

# %% auto #0
__all__ = ['INTENT_PATTERNS', 'classify_intent', 'classify_page_intents']

# %% ../../nbs/12b_insights_intent.ipynb
from sqlmodel import Session
from ..gsc.queries import get_top_queries


# %% ../../nbs/12b_insights_intent.ipynb
INTENT_PATTERNS = {
    "informational": [
        "what is",
        "how to",
        "guide",
        "explain",
        "tutorial",
        "ما هو",
        "كيف",
        "شرح",
        "تعريف",
        "دليل",
    ],
    "comparison": [
        "vs",
        "alternative",
        "best",
        "compare",
        "difference",
        "مقارنة",
        "أفضل",
        "بديل",
        "الفرق بين",
        "ضد",
    ],
    "transactional": [
        "buy",
        "price",
        "review",
        "specs",
        "discount",
        "سعر",
        "شراء",
        "مراجعة",
        "مواصفات",
        "طلب",
    ],
    "commercial": [
        "pricing",
        "cheapest",
        "affordable",
        "top rated",
        "comparison",
        "worth it",
        "cost",
        "budget",
        "rental",
        "أسعار",
        "أرخص",
        "تكلفة",
        "ميزانية",
        "إيجار",
    ],
    "navigational": [
        "site:",
        "login",
        "official",
        "website",
        "github",
        "موقع",
        "تسجيل دخول",
        "الرسمي",
    ],
}


# %% ../../nbs/12b_insights_intent.ipynb
def classify_intent(query: str
                    ) -> str:
    "Classify query intent based on keyword patterns."
    for intent, patterns in INTENT_PATTERNS.items():
        if any(p in query.lower() for p in patterns): return intent
    return "informational"

# %% ../../nbs/12b_insights_intent.ipynb
def classify_page_intents(session: Session,
                          site_url: str,
                          start_date: str,
                          end_date: str,
                          country: str | None = None,
                          page_path: str | None = None,
                          limit: int = 10
                          ) -> list[dict]:
    "Get top queries with intent classification."
    return [{**row, "intent": classify_intent(row["query"])}
            for row in get_top_queries(session, site_url, start_date, end_date,
                                       country=country, page_path=page_path, limit=limit)]

