"""Find missing queries and green keyword opportunities.

Docs: https://abdelkareemkobo.github.io/seootterinsights_keywords.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/12c_insights_keywords.ipynb.

# %% auto #0
__all__ = ['STOP_WORDS', 'filter_missing', 'query_words_in_content', 'all_missing_queries', 'FilterMissingQueries',
           'filter_missing_queries', 'find_green_keywords']

# %% ../../nbs/12c_insights_keywords.ipynb #e3842d6e
from sqlmodel import Session
from ..gsc.queries import get_top_queries
from .trends import detect_query_trends


# %% ../../nbs/12c_insights_keywords.ipynb #e657f8c9
STOP_WORDS = {
    "a",
    "an",
    "the",
    "is",
    "it",
    "in",
    "to",
    "for",
    "of",
    "and",
    "or",
    "how",
    "what",
    "who",
    "which",
    "this",
    "that",
    "هل",
    "في",
    "من",
    "على",
    "هو",
    "هذا",
    "ما",
}

def query_words_in_content(query: str,
                           content: str
                           ) -> bool:
    "Check if all significant words from a query appear in the content."
    words = [w for w in query.lower().split() if w not in STOP_WORDS and len(w) > 1]
    return all(w in content.lower() for w in words)


# %% ../../nbs/12c_insights_keywords.ipynb #3740d6d9
from logging import Filter
import dspy


def all_missing_queries(queries: list[dict], content: str) -> list[dict]:
    "Find GSC queries whose significant words don't appear in the page content."
    return [q for q in queries if not query_words_in_content(q["query"], content)]


class FilterMissingQueries(dspy.Signature):
    """Filter a list of search queries to only those relevant to the article topic."""

    queries: list[str] = dspy.InputField(
        desc="List of missing search queries to evaluate"
    )
    focus_keyword: str = dspy.InputField(desc="Main topic of the article")
    secondary_keywords: list[str] = dspy.InputField(desc="Related subtopics")
    content_snippet: str = dspy.InputField(desc="First 500 chars of article content")

    relevant_queries: list[str] = dspy.OutputField(
        desc="Only the queries relevant to this article's topic"
    )


filter_missing = dspy.Predict(FilterMissingQueries)


def filter_missing_queries(
    queries: list[str],
    focus_keyword: str,
    secondary_keywords: list,
    content: str,
) -> list[str]:
    """Filter missing queries in one batched DSPy call."""
    if not queries:
        return []
    result = filter_missing(
        queries=queries,
        focus_keyword=focus_keyword,
        secondary_keywords=secondary_keywords,
        content_snippet=content[:500],
    )
    return result.relevant_queries



# %% ../../nbs/12c_insights_keywords.ipynb #4883a0f0
def find_green_keywords(
    session: Session,
    site_url: str,
    page_path: str,
    content: str,
    days: int = 30,
    limit: int = 100,
) -> list[dict]:
    "Find emerging queries not yet covered in page content."
    trends = detect_query_trends(
        session, site_url, page_path=page_path, days=days, limit=limit
    )
    rising = [
        t for t in trends if t["trend"] == "rising" and t["prev_impressions"] <= 5
    ]
    return all_missing_queries(rising, content)

