"""Generate optimized SEO fields for Wuilt products using DSPy.

Docs: https://abdelkareemkobo.github.io/seootterwuilt_optimizer.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/23_wuilt_optimizer.ipynb.

# %% auto #0
__all__ = ['GenerateProductSEO', 'GenerateStoreSEO', 'GeneratePageSEO', 'GenerateRobotsTxt', 'optimize_product',
           'optimize_and_push', 'batch_optimize_products']

# %% ../../nbs/23_wuilt_optimizer.ipynb #imports
import os, dspy
from .client import WuiltClient
from ..dspy_infer import configure_lm

# %% ../../nbs/23_wuilt_optimizer.ipynb #signature
class GenerateProductSEO(dspy.Signature):
    """You are an e-commerce SEO expert. Generate optimized SEO fields for a product based on its current content."""
    title: str = dspy.InputField(desc="Current product title")
    description_html: str = dspy.InputField(desc="Current product description HTML")
    short_description: str = dspy.InputField(desc="Current short product description")
    language: str = dspy.InputField(desc="Language code e.g. 'en', 'ar'")
    seo_title: str = dspy.OutputField(desc="Optimized SEO title (50-60 characters, include focus keyword, brand name at end)")
    seo_description: str = dspy.OutputField(desc="Optimized meta description (150-160 characters, compelling with CTA, include keyword)")
    optimized_description_html: str = dspy.OutputField(desc="Improved product description HTML — benefit-driven, scannable, rich formatting, include keywords naturally")
    optimized_short_description: str = dspy.OutputField(desc="Concise value proposition (2-3 sentences, highlight unique benefit)")

# %% ../../nbs/23_wuilt_optimizer.ipynb #store-seo-sig
class GenerateStoreSEO(dspy.Signature):
    """You are an e-commerce SEO expert. Generate optimized SEO fields for a store."""
    store_name: str = dspy.InputField(desc="Current store name")
    language: str = dspy.InputField(desc="Language code e.g. 'en', 'ar'")
    seo_title: str = dspy.OutputField(desc="Optimized store-level SEO title (50-60 chars, include brand)")
    seo_description: str = dspy.OutputField(desc="Optimized store-level meta description (150-160 chars)")


# %% ../../nbs/23_wuilt_optimizer.ipynb #page-seo-sig
class GeneratePageSEO(dspy.Signature):
    """You are an e-commerce SEO expert. Generate optimized SEO fields for a store page."""
    page_name: str = dspy.InputField(desc="Current page name")
    page_type: str = dspy.InputField(desc="Page type: HOME or CUSTOM")
    language: str = dspy.InputField(desc="Language code e.g. 'en', 'ar'")
    seo_title: str = dspy.OutputField(desc="Optimized page SEO title (50-60 chars)")
    seo_description: str = dspy.OutputField(desc="Optimized page meta description (150-160 chars)")


# %% ../../nbs/23_wuilt_optimizer.ipynb #robots-sig
class GenerateRobotsTxt(dspy.Signature):
    """You are an SEO expert. Generate an optimized robots.txt for an e-commerce store."""
    store_name: str = dspy.InputField(desc="Store name")
    store_domain: str = dspy.InputField(desc="Store domain")
    language: str = dspy.InputField(desc="Language code e.g. 'en', 'ar'")
    robots_content: str = dspy.OutputField(desc="Complete robots.txt content with User-agent, Disallow, Allow, Sitemap directives")


# %% ../../nbs/23_wuilt_optimizer.ipynb #optimize-fn
def optimize_product(
    product_title: str,
    description_html: str = "",
    short_description: str = "",
    language: str = "en",
) -> dict:
    "Generate optimized SEO fields for a single product using DSPy."
    configure_lm()
    predictor = dspy.Predict(GenerateProductSEO)
    truncated_desc = description_html[:2000]
    truncated_short = short_description[:500]
    result = predictor(
        title=product_title[:200],
        description_html=truncated_desc,
        short_description=truncated_short,
        language=language,
    )
    return {
        "seo_title": result.seo_title,
        "seo_description": result.seo_description,
        "optimized_description_html": result.optimized_description_html,
        "optimized_short_description": result.optimized_short_description,
    }

# %% ../../nbs/23_wuilt_optimizer.ipynb #push-fn
def optimize_and_push(
    client: WuiltClient,
    product_id: str,
    product_title: str,
    description_html: str = "",
    short_description: str = "",
    language: str = "en",
) -> dict:
    "Generate optimized SEO for a product and push it back to Wuilt."
    optimized = optimize_product(
        product_title=product_title,
        description_html=description_html,
        short_description=short_description,
        language=language,
    )
    result = client.update_product_seo(
        product_id=product_id,
        seo_title=optimized["seo_title"],
        seo_description=optimized["seo_description"],
        description_html=optimized["optimized_description_html"],
        short_description=optimized["optimized_short_description"],
    )
    return {
        "optimized": optimized,
        "push_result": result,
    }

# %% ../../nbs/23_wuilt_optimizer.ipynb #batch-fn
def batch_optimize_products(
    api_key: str,
    store_id: str,
    locale: str = "ar",
    product_ids: list[str] | None = None,
) -> list[dict]:
    "Optimize SEO for all (or specified) products in a store and push to Wuilt."
    client = WuiltClient(api_key=api_key, store_id=store_id, locale=locale)
    products = client.get_products()

    if product_ids:
        products = [p for p in products if p["id"] in product_ids]

    results = []
    for p in products:
        print(f"Optimizing: {p['title']} ({p['id']})")
        seo = p.get("seo") or {}
        try:
            result = optimize_and_push(
                client=client,
                product_id=p["id"],
                product_title=p.get("title", ""),
                description_html=p.get("descriptionHtml", ""),
                short_description=p.get("shortDescription", ""),
                language=locale,
            )
            result["product_id"] = p["id"]
            result["title"] = p["title"]
            result["old_seo"] = seo
            results.append(result)
            print(f"  -> SEO title: {result['optimized']['seo_title'][:60]}...")
        except Exception as e:
            print(f"  FAILED: {e}")
            results.append({"product_id": p["id"], "title": p["title"], "error": str(e)})

    return results
