"""FastHTML routes for managing Wuilt stores and products.

Docs: https://abdelkareemkobo.github.io/seootterwuilt_routes.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/25_wuilt_routes.ipynb.

# %% auto #0
__all__ = ['app', 'rt', 'get', 'post']

# %% ../../nbs/25_wuilt_routes.ipynb #imports
from fasthtml.common import *
from seootter.models import (
    add_or_update_wuilt_store, get_wuilt_products, get_wuilt_pages, print_wuilt_products,
    WuiltStore, WuiltProduct, WuiltPage, delete_wuilt_store, print_wuilt_stores,
)
from ..sqlite_db import get_session
from .sync import sync_wuilt_products, sync_wuilt_pages
from dotenv import load_dotenv
import os

load_dotenv()


# %% ../../nbs/25_wuilt_routes.ipynb #app-setup
app, rt = fast_app()

# %% ../../nbs/25_wuilt_routes.ipynb #store-list
@rt("/")
def get():
    with get_session() as session:
        stores = session.exec(select(WuiltStore)).all()
    return Titled(
        "Wuilt Stores",
        Div(
            H2("Wuilt Store Manager"),
            A("Add Store", href="/add", style="margin-left: 1rem"),
            style="display: flex; align-items: center;"
        ),
        Table(
            Tr(Th("ID"), Th("Name"), Th("Store ID"), Th("Locale"), Th("Actions")),
            *[Tr(
                Td(str(s.id)),
                Td(s.name),
                Td(s.store_id),
                Td(s.locale),
                Td(
                    A("Products", href=f"/stores/{s.id}"),
                    " | ",
                    A("Sync", href=f"/sync/{s.id}"),
                    " | ",
                    A("Delete", href=f"/delete/{s.id}",
                      hx_confirm="Delete this store?"),
                ),
            ) for s in stores],
        ) if stores else P("No stores registered yet."),
        Br(),
        A("Back to Home", href="/"),
    )

# %% ../../nbs/25_wuilt_routes.ipynb #add-store
@rt("/add")
def get():
    return Titled(
        "Add Wuilt Store",
        Form(
            Label("Store Name:", Input(name="name", placeholder="My Store")),
            Label("Store ID:", Input(name="store_id", placeholder="Store_...")),
            Label("API Key:", Input(name="api_key", type="password")),
            Label("Locale:", Input(name="locale", value="ar", placeholder="ar")),
            Label("Store Domain:", Input(name="store_domain", placeholder="example.com")),
            Button("Save", type="submit"),
            action="/add", method="post",
        ),
        A("Back", href="/"),
    )


@rt("/add")
def post(name: str, store_id: str, api_key: str, locale: str = "ar", store_domain: str = ""):
    with get_session() as session:
        add_or_update_wuilt_store(
            session=session,
            store_id=store_id,
            name=name,
            api_key=api_key,
            locale=locale,
            store_domain=store_domain,
        )
        session.commit()
    return RedirectResponse("/", status_code=303)

# %% ../../nbs/25_wuilt_routes.ipynb #product-list
@rt("/stores/{store_pk:int}")
def get(store_pk: int):
    with get_session() as session:
        store = session.get(WuiltStore, store_pk)
        products = session.exec(
            select(WuiltProduct).where(WuiltProduct.wuilt_store_id == store_pk)
        ).all()
        pages = session.exec(
            select(WuiltPage).where(WuiltPage.wuilt_store_id == store_pk)
        ).all()
    if not store:
        return Titled("Error", P("Store not found"), A("Back", href="/"))
    return Titled(
        f"Store — {store.name}",
        A("← Back to stores", href="/"),
        Br(), Br(),
        H3("Products"),
        Table(
            Tr(Th("Title"), Th("Handle"), Th("SEO Title"), Th("Synced")),
            *[Tr(
                Td(p.title),
                Td(p.handle),
                Td(p.seo_title or "-"),
                Td(p.synced_at.strftime("%Y-%m-%d") if p.synced_at else "-"),
            ) for p in products],
        ) if products else P("No products synced yet."),
        Br(),
        A("Sync Products", href=f"/sync/{store_pk}"),
        Br(), Br(),
        H3("Pages"),
        Table(
            Tr(Th("Name"), Th("Handle"), Th("Type"), Th("Status"), Th("SEO Title")),
            *[Tr(
                Td(p.name),
                Td(p.handle),
                Td(p.page_type),
                Td(P(p.status, style="color: green" if p.status == "PUBLISHED" else "orange")),
                Td(p.seo_title or "-"),
            ) for p in pages],
        ) if pages else P("No pages synced yet."),
        Br(),
        A("Sync Pages", href=f"/sync-pages/{store_pk}"),
    )


# %% ../../nbs/25_wuilt_routes.ipynb #sync-route
@rt("/sync/{store_pk:int}")
def get(store_pk: int):
    with get_session() as session:
        store = session.get(WuiltStore, store_pk)
    if not store:
        return Titled("Error", P("Store not found"), A("Back", href="/"))
    result = sync_wuilt_products(
        api_key=store.api_key,
        store_id=store.store_id,
        store_name=store.name,
        locale=store.locale,
    )
    return Titled(
        "Sync Complete",
        P(f"Products: {result['total']} ({result['created']} new, {result['updated']} updated)"),
        A("← Back to store", href=f"/stores/{store_pk}"),
    )


# | export
@rt("/sync-pages/{store_pk:int}")
def get(store_pk: int):
    with get_session() as session:
        store = session.get(WuiltStore, store_pk)
    if not store:
        return Titled("Error", P("Store not found"), A("Back", href="/"))
    result = sync_wuilt_pages(
        api_key=store.api_key,
        store_id=store.store_id,
        store_name=store.name,
        locale=store.locale,
    )
    return Titled(
        "Sync Complete",
        P(f"Pages: {result['total']} ({result['created']} new, {result['updated']} updated)"),
        A("← Back to store", href=f"/stores/{store_pk}"),
    )


# %% ../../nbs/25_wuilt_routes.ipynb #delete-route
@rt("/delete/{store_pk:int}")
def get(store_pk: int):
    with get_session() as session:
        delete_wuilt_store(session, store_pk)
        session.commit()
    return RedirectResponse("/", status_code=303)
