"""DB-access functions for heavy computation: keyword density and cannibalization.

Docs: https://abdelkareemkobo.github.io/seoottercontent_analysis.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/10b_content_analysis.ipynb.

# %% auto #0
__all__ = ['calculate_keyword_density', 'find_cannibalized']

# %% ../../nbs/10b_content_analysis.ipynb #9844618a
def calculate_keyword_density(content: str,
                              keyword: str
                              ) -> dict:
    "Calculate keyword density using word-level matching."
    try:
        content_words = content.lower().split()
        keyword_words = keyword.lower().split()
        n = len(keyword_words)
        positions = [i for i in range(len(content_words) - n + 1)
                     if content_words[i:i + n] == keyword_words]
        total = len(content_words)
        return {"keyword": keyword, "count": len(positions),
                "density": (len(positions) / total * 100) if total > 0 else 0,
                "positions": positions}
    except Exception:
        return {"keyword": keyword, "count": 0, "density": 0.0, "positions": []}


# %% ../../nbs/10b_content_analysis.ipynb #f4be9bbf
from ..article import get_articles_by_website
from ..parser.utils import get_page_content
from ..sqlite_db import get_session
from ..models import GSCAnalytics
from ..gsc.queries import get_top_queries
from ..gsc_client import get_date_range
from sqlmodel import select


# %% ../../nbs/10b_content_analysis.ipynb #76c0794d
def find_cannibalized(session,
                      website_id: int,
                      site_url: str,
                      start: str,
                      end: str
                      ) -> dict:
    "Find keyword cannibalization via exact focus keyword matches and GSC ranking data."
    try:
        from collections import defaultdict
        articles = get_articles_by_website(session=session, website_id=website_id)
        kw_map = defaultdict(list)
        for a in articles:
            if a.focus_keyword: kw_map[a.focus_keyword].append(a.url)
        exact_matches = [{"keyword": kw, "pages": urls}
                         for kw, urls in kw_map.items() if len(urls) >= 2]
        gsc_matches = []
        for query in [r["query"] for r in get_top_queries(session, site_url, start, end, limit=1000)]:
            pages = session.exec(
                select(GSCAnalytics.page).where(
                    GSCAnalytics.site_url == site_url, GSCAnalytics.query == query,
                    GSCAnalytics.date.between(start, end), GSCAnalytics.position <= 20,
                ).distinct()
            ).all()
            if len(pages) >= 2: gsc_matches.append({"query": query, "pages": pages})
        return {"exact_matches": exact_matches, "gsc_matches": gsc_matches}
    except Exception:
        return {"exact_matches": [], "gsc_matches": []}
